version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=EquipeBD
      - POSTGRES_USER=equipefenix
      - POSTGRES_PASSWORD=equipefenix
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
