version: '3.9'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3300:3306

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    volumes:
      - .:/frameworkORM
    working_dir: /frameworkORM
